[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
amm = "7MFsykToLeEHYmfsxid2d7Fc9K1LApTB2y7QnGmfoZXX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
