[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
marketplace = "Ci69V3skg2YNxNUeH7WonV8RV5TeY8FXWJFyiw8ZcpL6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
