[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow = "B7xXE92N35vPUFQtxtJ9ycnDqLRw3HtKqjNSdKgG4CP8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
